#!/bin/bash
# Helper script to create Rema - Calm Down lyrics video

echo "=================================================="
echo "Rema - Calm Down Lyrics Video Creator"
echo "=================================================="
echo ""
echo "STEP 1: Get the LRC file"
echo "------------------------"
echo "Visit: https://www.megalobiz.com/lrc/maker/Rema+-+Calm+Down+(Official+Music+Video)(MP3_320K).55643056"
echo ""
echo "On that page:"
echo "1. You'll see the synchronized lyrics"
echo "2. Click 'Download LRC' button"
echo "3. Save as: ~/code/lyrics-video-tool/rema_calm_down.lrc"
echo ""
echo "STEP 2: Get or prepare the audio"
echo "---------------------------------"
echo "Make sure you have the audio file, for example:"
echo "  ~/Music/rema_calm_down.mp3"
echo ""
echo "STEP 3: Create the video"
echo "------------------------"
echo "Once you have both files, run:"
echo ""
echo "python create_video.py \\"
echo "  --audio ~/Music/rema_calm_down.mp3 \\"
echo "  --lrc rema_calm_down.lrc \\"
echo "  --output rema_calm_down_lyrics.mp4 \\"
echo "  --style center \\"
echo "  --font-size 70"
echo ""
echo "=================================================="
